version: '3'

services:
  socat:
    build:
      context: .
      dockerfile: jenkins_agent_dockerfile
    container_name: socat-container
    restart: always
    ports:
      - "2376:2375"
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    external: true
